name: orion
channels:
- anaconda
- conda-forge
- omnia-dev/label/cuda90 # openmm 7.5.0 required for SMIRNOFF support
- omnia
- OpenEye/label/Orion
- OpenEye
dependencies:
# general
- pip
- cookiecutter
# perses
- perses
# orion
- pip:
  - OpenEye-orionplatform==2.2.0
  - attrs==18.2.0
  - invoke==1.2.0
  - OpenEye-artemis==1.1.1
  - OpenEye-ensemble2img==0.1.1
  - OpenEye-floereport==0.1.5
  - OpenEye_oetrajanalysis==0.1.4.4
  - Openeye-toolkits==2019.10.2
  - pytest==3.10.1
  - six==1.12.0
  - wcwidth==0.1.7
