name: orion-perses
channels:
- conda-forge
- omnia/label/cuda100
- omnia
- OpenEye/label/Orion
dependencies:
# general
- pip==18.0
# perses
- perses==0.5.1
- pip:
# Leave this here to avoid pip install issues
  - OpenEye-orionplatform==2.4.4
  - OpenEye-artemis
  - attrs
  - invoke
  - Openeye-toolkits==2019.10.2
  - psutil==5.6.7
  - six==1.12.0
  - wcwidth==0.1.7
